# -*- coding: utf-8 -*-
"""Cópia de Cópia de 06_jogo_aventura_texto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wXzyU6d9eOz-UA25vCApTtI-Mi-IaLZT

# Encontro 6 — Jogo 4: Aventura em texto (história ramificada)

## Objetivos da aula
- Modelar cenas com funções.
- Criar escolhas e finais.
- Organizar o código em partes.

## Agenda (100 min)
- 10 min — exemplos
- 20 min — funções
- 55 min — criação
- 15 min — apresentação rápida

## Materiais
- Python 3.x + VS Code (ou Jupyter)
- Pasta `data/` (datasets) quando indicado

## Regras rápidas
- Use nomes de variáveis claros
- Comente **por quê** (não só o que)

👩‍🏫 **Versão do professor (com gabarito e notas)**

- Contém sugestões de solução e pontos de atenção.
- Ajuste o nível (mais guiado/mais aberto) conforme a turma.

## Notas didáticas
- **Checklist**: confirmar ambiente (Python/Jupyter), relembrar combinados.
- **Gestão de tempo**: use checkpoints a cada 15–20 min.
- **Avaliação formativa**: peça que cada dupla mostre 1 coisa que aprendeu.

## Estrutura sugerida

Cada cena é uma função. Retorne a próxima cena.
"""

def cena_inicio():
    print('Você acorda em uma sala...')
    op = input('1) Porta  2) Janela: ')
    return 'porta' if op=='1' else 'janela'

def cena_porta():
    print('A porta está trancada...')
    return 'fim'

def main():
    cena = 'inicio'
    while cena != 'fim':
        if cena == 'inicio':
            cena = cena_inicio()
        elif cena == 'porta':
            cena = cena_porta()
        else:
            cena = 'fim'
    print('Fim!')

main()

"""## Exercícios (entrega)
1. Crie ao menos 6 cenas e 2 finais diferentes.
2. Inclua inventário simples (lista) com 3 itens possíveis.
"""

# ✅ Espaço do aluno (para aplicar em sala)

"""## Gabarito (sugestão)
_Abaixo vai uma solução possível. Existem várias._
"""

# 🧩 Sugestão de caminho:
# 1) Quebre em funções pequenas.
# 2) Faça 1 caso funcionar.
# 3) Adicione validação e repita.

# Exemplo de estrutura (ajuste conforme o exercício):
def main():
    pass

if __name__ == '__main__':
    main()

"""### Erros comuns
- `ValueError` ao converter `int()` com entrada inválida → usar `try/except`.
- Laço infinito por falta de atualização de variável.
- Comparação de strings com espaços/capitalização → usar `.strip().lower()`.

## Bônus
- Adicione sistema de vida/pontuação (variável) e eventos que alteram o valor.

## Gabarito completo (Professor)

> Sugestão de solução pronta. Ajuste conforme a turma.
"""

# Gabarito — Aventura com 6 cenas, inventário e 2 finais

def escolher(msg, opcoes):
    while True:
        r = input(msg).strip().lower()
        if r in opcoes:
            return r
        print("⚠️ Opção inválida.")

state = {"vida": 3, "inv": []}

def pegar(item):
    if item not in state["inv"]:
        state["inv"].append(item)

def inicio():
    print("Você acorda em um laboratório abandonado.")
    op = escolher("1) Corredor  2) Armário: ", ["1","2"])
    return "corredor" if op=="1" else "armario"

def armario():
    print("No armário há uma lanterna e uma chave.")
    op = escolher("Pegar (l)anterna, (c)have ou (n)ada? ", ["l","c","n"])
    if op=="l": pegar("lanterna")
    if op=="c": pegar("chave")
    return "corredor"

def corredor():
    print("Há uma porta trancada e uma escada.")
    op = escolher("1) Porta  2) Escada: ", ["1","2"])
    return "porta" if op=="1" else "escada"

def porta():
    if "chave" in state["inv"]:
        print("Você usa a chave e abre a porta!")
        return "sala"
    else:
        print("A porta está trancada. Você se machuca tentando arrombar (-1 vida).")
        state["vida"] -= 1
        return "fim_ruim" if state["vida"] <= 0 else "corredor"

def escada():
    print("A escada leva ao telhado. Está escuro.")
    if "lanterna" in state["inv"]:
        print("Com a lanterna, você encontra uma saída segura!")
        return "fim_bom"
    else:
        print("Sem lanterna, você tropeça (-1 vida).")
        state["vida"] -= 1
        return "fim_ruim" if state["vida"] <= 0 else "corredor"

def sala():
    print("Na sala há um rádio com sinal fraco.")
    op = escolher("1) Pedir ajuda  2) Ignorar: ", ["1","2"])
    if op=="1":
        return "fim_bom"
    return "fim_ruim"

def fim_bom():
    print("✅ Você escapou! Inventário:", state["inv"])
    return "fim"

def fim_ruim():
    print("💀 Você não conseguiu sair. Inventário:", state["inv"])
    return "fim"

cenas = {
    "inicio": inicio,
    "armario": armario,
    "corredor": corredor,
    "porta": porta,
    "escada": escada,
    "sala": sala,
    "fim_bom": fim_bom,
    "fim_ruim": fim_ruim,
}

cena = "inicio"
while cena != "fim":
    cena = cenas[cena]()

import sys


# ==========================================
# FUNÇÃO PARA ESCOLHER
# ==========================================

def escolher(msg, opcoes):
    while True:
        resposta = input(msg).strip()

        if resposta in opcoes:
            return resposta

        print("⚠️ Opção inválida. Tente novamente.")


# ==========================================
# VARIÁVEIS DO JOGO
# ==========================================

Ajuda = False
Entrar_floresta = False
Ajudar_Lyra = False

checkpoint = 1


# ==========================================
# GAME OVER
# ==========================================

def game_over():
    print("\n" + "=" * 40)
    print("💀 GAME OVER!")
    print("=" * 40)

    op = escolher(
        "\nDeseja tentar novamente?\n"
        "1) Sim\n"
        "2) Não\n"
        "Escolha: ",
        ["1", "2"]
    )

    if op == "1":
        voltar_checkpoint()

    else:
        print("\nObrigado por jogar As Crônicas de Aetherion! ⚔️")
        sys.exit()


# ==========================================
# VOLTAR AO CHECKPOINT
# ==========================================

def voltar_checkpoint():

    if checkpoint == 1:
        nivel_1()

    elif checkpoint == 2:
        nivel_2()

    elif checkpoint == 3:
        nivel_3()

    elif checkpoint == 4:
        nivel_4()

    elif checkpoint == 5:
        nivel_5()

    elif checkpoint == 6:
        nivel_6()

    elif checkpoint == 7:
        nivel_7()


# ==========================================
# NÍVEL 1 — FLORESTA DE ELDORIA
# ==========================================

def nivel_1():

    global checkpoint
    global Ajuda
    global Entrar_floresta

    checkpoint = 1

    print("\n🌳 NÍVEL 1 — FLORESTA DE ELDORIA")

    print("O feiticeiro Mordrak tentou roubar o poder dos cristais.")
    print("Os antigos guardiões conseguiram derrotá-lo.")
    print("Agora o selo está enfraquecendo e monstros voltaram.")
    print("Você é o novo escolhido pelos deuses.")

    print("\nVocê chega a uma vila próxima à floresta.")
    print("Monstros estão atacando os moradores.")

    op = escolher(
        "\n1) Ajudar os moradores"
        "\n2) Entrar diretamente na floresta"
        "\nEscolha: ",
        ["1", "2"]
    )

    if op == "1":

        Ajuda = True

        print("\nVocê enfrenta as criaturas.")
        print("Os moradores agradecem e prometem ajudá-lo futuramente.")

    elif op == "2":

        Entrar_floresta = True

        print("\nVocê ignora a batalha e entra na floresta.")
        print("Você encontra um caminho mais rápido.")

    nivel_2()


# ==========================================
# NÍVEL 2 — TEMPLO DA TERRA
# ==========================================

def nivel_2():

    global checkpoint

    checkpoint = 2

    print("\n🌍 NÍVEL 2 — TEMPLO DA TERRA")

    print("Ao chegar ao Templo da Terra, você encontra dois caminhos.")

    op = escolher(
        "\n1) Caminho da Esquerda"
        "\n2) Caminho da Direita"
        "\nEscolha: ",
        ["1", "2"]
    )

    if op == "1":

        print("\nVocê entra na sala.")
        print("A porta se fecha.")
        print("As paredes começam a se mover em sua direção.")

        game_over()
        return

    elif op == "2":

        print("\nVocê passa pelo corredor.")
        print("Uma sala cheia de criaturas de pedra aparece.")

        op = escolher(
            "\n1) Enfrentá-los"
            "\n2) Tentar passar por eles"
            "\nEscolha: ",
            ["1", "2"]
        )

        if op == "1":

            print("\nVocê derrota as criaturas.")
            print("No final do templo, você encontra o Cristal da Terra!")

        elif op == "2":

            print("\nVocê consegue passar rapidamente pelos inimigos.")
            print("No final do templo, você encontra o Cristal da Terra!")

    nivel_3()


# ==========================================
# NÍVEL 3 — MONTANHAS DE FROSTPEAK
# ==========================================

def nivel_3():

    global checkpoint
    global Ajudar_Lyra

    checkpoint = 3

    print("\n❄️ NÍVEL 3 — MONTANHAS DE FROSTPEAK")

    print("Você viaja até as montanhas congeladas.")
    print("No caminho, encontra uma guerreira chamada Lyra.")
    print("Ela está sendo atacada por monstros.")

    op = escolher(
        "\n1) Ajudar Lyra"
        "\n2) Continuar sozinho"
        "\nEscolha: ",
        ["1", "2"]
    )

    if op == "1":

        Ajudar_Lyra = True

        print("\nVocê ajuda Lyra.")
        print("Ela agradece e decide acompanhá-lo.")

    elif op == "2":

        print("\nVocê continua sua jornada sozinho.")

    print("\nApós atravessar as montanhas, você encontra o Templo da Água.")
    print("Depois de superar o guardião, você conquista o Cristal da Água!")

    nivel_4()


# ==========================================
# NÍVEL 4 — VULCÃO INFERNIS
# ==========================================

def nivel_4():

    global checkpoint

    checkpoint = 4

    print("\n🌋 NÍVEL 4 — VULCÃO INFERNIS")

    print("Você chega ao vulcão onde está o terceiro cristal.")
    print("Um poderoso Guardião de Fogo aparece.")

    op = escolher(
        "\n1) Atacar diretamente"
        "\n2) Usar os cristais"
        "\nEscolha: ",
        ["1", "2"]
    )

    if op == "1":

        print("\nVocê tenta atacar o Guardião.")
        print("Ele contra-ataca e você é lançado para dentro da lava.")

        game_over()
        return

    elif op == "2":

        print("\nVocê combina os poderes dos cristais.")
        print("Usando uma estratégia elemental, você derrota o Guardião.")
        print("🔥 Você conquista o Cristal do Fogo!")

    nivel_5()


# ==========================================
# NÍVEL 5 — CORRIDA NO TORNADO
# ==========================================

def nivel_5():

    global checkpoint

    checkpoint = 5

    print("\n🌪️ NÍVEL 5 — O TORNADO DOS VENTOS")

    print("Você segue em busca do último cristal.")
    print("De repente, um enorme tornado aparece.")
    print("Você é puxado para dentro dele.")

    print("\nDentro do tornado está o Guardião do Ar.")

    print("""
Ele diz:

'Vamos apostar uma corrida até o topo.
Quem chegar primeiro às nuvens vence.

Se você ganhar, ficará com o Cristal do Ar.
Se eu ganhar, ficarei com todos os seus cristais.'
""")

    op = escolher(
        "\n1) Aceitar a corrida"
        "\n2) Recusar e atacar"
        "\nEscolha: ",
        ["1", "2"]
    )

    if op == "2":

        print("\nVocê tenta atacar o Guardião.")
        print("Ele rouba seus cristais e o lança para fora do tornado.")

        game_over()
        return

    elif op == "1":

        print("\nA corrida começa!")

        print("Você usa os cristais para criar caminhos.")
        print("Você está prestes a ultrapassar o Guardião.")

        print("\nMas ele começa a lançar destroços em sua direção!")

        op = escolher(
            "\n1) Usar o Cristal da Terra"
            "\n2) Usar o Cristal da Água"
            "\n3) Usar o Cristal do Fogo"
            "\nEscolha: ",
            ["1", "2", "3"]
        )

        if op == "1":

            print("\nVocê tenta criar mais caminhos de terra.")
            print("Mas as estruturas perdem estabilidade.")
            print("Você cai do tornado.")

            game_over()
            return

        elif op == "2":

            print("\nVocê cria caminhos de gelo.")
            print("Porém eles se tornam instáveis.")
            print("Você cai do tornado.")

            game_over()
            return

        elif op == "3":

            print("\nVocê reúne todo o calor ao seu redor.")
            print("🔥 Você se impulsiona pelo tornado em alta velocidade!")
            print("Você chega às nuvens antes do Guardião!")

            print("""
O Guardião olha para você e diz:

'Eu nunca vi alguém com tanta estratégia e agilidade.
A vitória é sua. Fique com o cristal.'
""")

            print("🌪️ Você conquista o Cristal do Ar!")

    nivel_6()


# ==========================================
# NÍVEL 6 — CASTELO SOMBRIO
# ==========================================

def nivel_6():

    global checkpoint

    checkpoint = 6

    print("\n🏰 NÍVEL 6 — CASTELO SOMBRIO")

    print("Você finalmente chega ao Castelo Sombrio.")
    print("Vários guardas protegem a entrada.")

    # Se o jogador ajudou os moradores ou Lyra
    if Ajuda or Ajudar_Lyra:

        op = escolher(
            "\n1) Enfrentar os guardas"
            "\n2) Pedir ajuda aos aliados"
            "\nEscolha: ",
            ["1", "2"]
        )

        if op == "1":

            print("\nVocê usa seus poderes e derrota os guardas.")

        elif op == "2":

            print("\nSeus aliados ajudam a distrair os guardas.")
            print("Você consegue entrar no castelo.")

    else:

        print("\nVocê está sozinho.")
        print("Usando os quatro cristais, você derrota os guardas.")

    nivel_7()


# ==========================================
# NÍVEL 7 — BATALHA CONTRA MORDRAK
# ==========================================

def nivel_7():

    global checkpoint

    checkpoint = 7

    print("\n👑 NÍVEL 7 — MORDRAK")

    print("Você entra no castelo.")
    print("Mordrak está esperando por você.")

    print("""
A batalha começa!

Mordrak copia parte de seus poderes elementais
e lança uma poderosa bola de fogo negro.
""")

    op = escolher(
        "\n1) Defender-se"
        "\n2) Desviar e contra-atacar"
        "\nEscolha: ",
        ["1", "2"]
    )

    if op == "1":

        print("\nVocê cria uma parede de pedra.")
        print("Mas a chama negra atravessa a defesa.")

        game_over()
        return

    elif op == "2":

        print("\nVocê usa o poder do fogo para se desviar.")
        print("Em seguida, contra-ataca Mordrak!")

        print("\nMordrak cria nuvens carregadas de trovões negros.")

        op = escolher(
            "\n1) Rebater as nuvens usando o vento"
            "\n2) Criar um escudo de pedra"
            "\nEscolha: ",
            ["1", "2"]
        )

        if op == "2":

            print("\nOs raios atravessam sua defesa.")

            game_over()
            return

        elif op == "1":

            print("\nVocê usa o poder do Ar para afastar as nuvens.")

            print("""
Mordrak abre um portal.

Você é preso em uma ilusão.

Cinco versões de Mordrak aparecem.
""")

            op = escolher(
                "\n1) Atacar um dos clones"
                "\n2) Usar seus poderes"
                "\nEscolha: ",
                ["1", "2"]
            )

            if op == "1":

                print("\nOs clones são feitos de sombras.")
                print("Você não consegue acertá-los.")

                game_over()
                return

            elif op == "2":

                print("\nVocê reúne energia e cria uma explosão elemental.")
                print("A ilusão é destruída!")

                print("""
Mordrak assume sua Forma de Rei Sombrio.

Ele usa seu ataque mais poderoso:

🌑 ECLIPSE FINAL!
""")

                op = escolher(
                    "\n1) Tentar rebater"
                    "\n2) Unir o poder dos quatro cristais"
                    "\nEscolha: ",
                    ["1", "2"]
                )

                if op == "1":

                    print("\nVocê tenta rebater o ataque.")
                    print("Mas o poder de Mordrak é forte demais.")

                    game_over()
                    return

                elif op == "2":

                    print("\nVocê une os quatro Cristais Elementais!")

                    print("""
🌍 Terra
🌊 Água
🔥 Fogo
🌪️ Ar

Os quatro elementos começam a se unir.

Um novo cristal é criado:

✨ O CRISTAL DE ARCHÉ! ✨
""")

                    print("""
O Cristal de Arché concede uma nova forma:

⚡ ARCHÉ FORM ⚡

Com o poder dos quatro elementos unidos,
você derrota Mordrak e restaura o equilíbrio
de Aetherion!

🏆 PARABÉNS! VOCÊ ZEROU O JOGO!
""")

                    print("\nObrigado por jogar! ⚔️")
                    return


# ==========================================
# INICIAR O JOGO
# ==========================================

def iniciar_jogo():

    print("=" * 50)
    print("⚔️ AS CRÔNICAS DE AETHERION ⚔️")
    print("=" * 50)

    nivel_1()


iniciar_jogo()